
# AllCops:
#   DisabledByDefault: false

# Style/Encoding:
#   Enabled: true

# Layout/LineLength:
#   Max: 80

# Layout/SpaceAroundMethodCallOperator:
#   Enabled: true
# Lint/RaiseException:
#   Enabled: true
# Lint/StructNewOverride:
#   Enabled: true
# Style/ExponentialNotation:
#   Enabled: true
# Style/HashEachMethods:
#   Enabled: true
# Style/HashTransformKeys:
#   Enabled: true
# Style/HashTransformValues:
#   Enabled: true

#    _____               ____ ____        __     _         __
#   / ___/ _____ ____ _ / __// __/____   / /    (_)____   / /_
#   \__ \ / ___// __ `// /_ / /_ / __ \ / /    / // __ \ / __/
#  ___/ // /__ / /_/ // __// __// /_/ // /___ / // / / // /_
# /____/ \___/ \__,_//_/  /_/ 1 \____//_____//_//_/ /_/ \__/
#
# The linter file that doesn't lead junior developers to bad habits.
# https://github.com/makersacademy/scaffolint
#
# Configure Rubocop to use the config file in the Scaffolint GitHub repo
inherit_from:
  - https://raw.githubusercontent.com/makersacademy/scaffolint/v1.1.0/.rubocop.yml